//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabourTimeTable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class complaint
    {
        public string com_no { get; set; }
        public Nullable<System.DateTime> trandate { get; set; }
        public Nullable<System.DateTime> com_date { get; set; }
        public string com_source { get; set; }
        public string com_job { get; set; }
        public string ac_code { get; set; }
        public string com_name { get; set; }
        public Nullable<int> com_id { get; set; }
        public string com_narration { get; set; }
        public string com_type { get; set; }
        public Nullable<long> ac_sub { get; set; }
        public string com_person { get; set; }
        public string com_phone { get; set; }
        public string com_rec_by { get; set; }
        public string com_iss_to { get; set; }
        public string com_iss_time { get; set; }
        public string com_status { get; set; }
        public string doc_no { get; set; }
        public string jobsystemId { get; set; }
        public string enq_no { get; set; }
        public Nullable<System.DateTime> date_done { get; set; }
        public Nullable<long> cust_rep { get; set; }
        public string Sheetno { get; set; }
        public string techproblem { get; set; }
        public string techsolution { get; set; }
        public Nullable<bool> Priority { get; set; }
        public Nullable<byte> doc_level { get; set; }
        public string doc_status { get; set; }
        public string user_name { get; set; }
        public string remarks { get; set; }
        public string Job_name { get; set; }
        public Nullable<bool> IsOldJob { get; set; }
        public Nullable<double> com_Amount { get; set; }
        public Nullable<double> Credit { get; set; }
        public string doc_noNew { get; set; }
    }
}
