//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabourTimeTable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact
    {
        public decimal ac_sub { get; set; }
        public string ac_code { get; set; }
        public string Empname { get; set; }
        public string Ac_name { get; set; }
        public string Designation { get; set; }
        public string Deptname { get; set; }
        public string Influence { get; set; }
        public string Telno { get; set; }
        public string Mobno { get; set; }
        public string Faxno { get; set; }
        public string Email { get; set; }
        public string Voip { get; set; }
        public string Company { get; set; }
        public string jobno { get; set; }
    }
}
