//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabourTimeTable.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InterfutureEntities : DbContext
    {
        public InterfutureEntities()
            : base("name=InterfutureEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<employee> employees { get; set; }
        public DbSet<enq_mast> enq_mast { get; set; }
        public DbSet<enq_tran> enq_tran { get; set; }
        public DbSet<joblabcost> joblabcosts { get; set; }
        public DbSet<joblabwork> joblabworks { get; set; }
        public DbSet<OutSourceDetail> OutSourceDetails { get; set; }
        public DbSet<JobLabWorkTemp> JobLabWorkTemps { get; set; }
        public DbSet<empTmp> empTmps { get; set; }
        public DbSet<jobplanday> jobplandays { get; set; }
        public DbSet<JobDailyProduction> JobDailyProductions { get; set; }
        public DbSet<joblabworkemp> joblabworkemps { get; set; }
    }
}
