//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabourTimeTable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public string AC_CODE { get; set; }
        public string AC_NAME { get; set; }
        public Nullable<decimal> AC_BAL { get; set; }
        public string AC_ADDRESS { get; set; }
        public string AC_POBOX { get; set; }
        public Nullable<int> AC_CITYID { get; set; }
        public string AC_CITY { get; set; }
        public Nullable<int> AC_COUNTRYID { get; set; }
        public string AC_COUNTRY { get; set; }
        public string AC_TELE1 { get; set; }
        public string AC_TELE2 { get; set; }
        public string AC_MOBNO { get; set; }
        public string AC_FAXNO { get; set; }
        public string AC_CONTACT { get; set; }
        public string AC_EMAIL { get; set; }
        public string AC_WEBSITE { get; set; }
        public Nullable<short> AC_TERMS { get; set; }
        public Nullable<int> AC_TYPE { get; set; }
        public Nullable<int> AC_SMAN { get; set; }
        public Nullable<int> ctype { get; set; }
        public string DISC_PER { get; set; }
        public string SHIP_TO { get; set; }
        public Nullable<bool> Nonactive { get; set; }
        public Nullable<decimal> War_Type { get; set; }
        public string PassExcel { get; set; }
        public string AccCode { get; set; }
        public Nullable<decimal> CostType { get; set; }
        public Nullable<decimal> @bool { get; set; }
        public Nullable<decimal> id { get; set; }
    }
}
