//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabourTimeTable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobLabWorkTemp
    {
        public long ID { get; set; }
        public string TaskName { get; set; }
        public Nullable<double> PlanTime { get; set; }
        public Nullable<double> Worjtime { get; set; }
        public Nullable<double> Balance { get; set; }
    }
}
