//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabourTimeTable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jobplanday
    {
        public long Id { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<System.DateTime> trandate { get; set; }
        public string Jobno { get; set; }
        public string JobsystemId { get; set; }
        public Nullable<short> trantime { get; set; }
        public Nullable<byte> Jobcode { get; set; }
        public string doc_no { get; set; }
        public string jobWork { get; set; }
        public Nullable<decimal> timealloc { get; set; }
        public Nullable<long> JobPlanMonthId { get; set; }
        public Nullable<int> PlanNo { get; set; }
    }
}
