//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabourTimeTable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutSourceDetail
    {
        public long id { get; set; }
        public string doc_no { get; set; }
        public string jobno { get; set; }
        public string jobsystemid { get; set; }
        public Nullable<System.DateTime> jobdate { get; set; }
        public Nullable<int> noOfOutsource { get; set; }
        public Nullable<System.DateTime> fromtime { get; set; }
        public Nullable<System.DateTime> totime { get; set; }
        public string companyName { get; set; }
    }
}
