//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabourTimeTable.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TimesheetEntities : DbContext
    {
        public TimesheetEntities()
            : base("name=TimesheetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<employee> employees { get; set; }
        public DbSet<enq_mast> enq_mast { get; set; }
        public DbSet<enq_tran> enq_tran { get; set; }
        public DbSet<JobDailyProduction> JobDailyProductions { get; set; }
        public DbSet<joblabcost> joblabcosts { get; set; }
        public DbSet<joblabwork> joblabworks { get; set; }
        public DbSet<OutSourceDetail> OutSourceDetails { get; set; }
        public DbSet<JobLabWorkTemp> JobLabWorkTemps { get; set; }
        public DbSet<jobplanday> jobplandays { get; set; }
        public DbSet<ts_employee> ts_employee { get; set; }
        public DbSet<ts_user> ts_user { get; set; }
        public DbSet<empTmp> empTmps { get; set; }
        public DbSet<joblabworkemp> joblabworkemps { get; set; }
        public DbSet<complaint> complaints { get; set; }
        public DbSet<complaintname> complaintnames { get; set; }
        public DbSet<complainttype> complainttypes { get; set; }
        public DbSet<contact> contacts { get; set; }
        public DbSet<customer> customers { get; set; }
        public DbSet<WorkInProgress> WorkInProgresses { get; set; }
        public DbSet<ts_timesheet_com> ts_timesheet_com { get; set; }
        public DbSet<ac_system> ac_system { get; set; }
        public DbSet<ac_dept> ac_dept { get; set; }
        public DbSet<activitysub> activitysubs { get; set; }
        public DbSet<ts_timesheet_enq> ts_timesheet_enq { get; set; }
        public DbSet<ts_place> ts_place { get; set; }
        public DbSet<ts_emirates_id> ts_emirates_id { get; set; }
        public DbSet<ts_timesheet> ts_timesheet { get; set; }
    }
}
