//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabourTimeTable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ts_emirates_id
    {
        public long id { get; set; }
        public string emirates_id { get; set; }
        public string empID { get; set; }
        public string empname { get; set; }
    }
}
