//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabourTimeTable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ts_place
    {
        public long id { get; set; }
        public string ts_timesheet_groupid { get; set; }
        public string latlang { get; set; }
        public string name { get; set; }
        public string adr_address { get; set; }
        public string formatted_address { get; set; }
    }
}
