//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabourTimeTable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ts_timesheet_enq
    {
        public int id { get; set; }
        public string userid { get; set; }
        public string emp_id { get; set; }
        public string enq_no { get; set; }
        public string cust_name { get; set; }
        public string project_name { get; set; }
        public string department { get; set; }
        public string purpose { get; set; }
        public string checkin { get; set; }
        public string checkout { get; set; }
        public string time { get; set; }
        public string place { get; set; }
        public string remarks { get; set; }
        public Nullable<bool> is_checkout { get; set; }
        public string createdby { get; set; }
        public string groupid { get; set; }
        public Nullable<System.DateTime> ondate_created { get; set; }
    }
}
